# Логирование
logging:
  level:
    org.springframework: info
    org.hibernate.sql: info
    org.hibernate.type: info
    org.hibernate.type.descriptor: info
    org.hibernate.pretty: info
    org.springframework.orm: info
    org.springframework.web: info

# Настройки Сервера
server:
  port: 7002

# provider
db_adapter:
  wait_on_stop_ms: 1000
  min_time_per_iteration_ms: 50
  timeout_life_ms: 10000

#kafka
kafka:
  server: localhost:9092
  group:
    id: quik-group
  income_topic:
    all_trades: quikProviderAllTrades
    deals: quikProviderDeals
    orders: quikProviderOrders

#data
spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    show-sql: false
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: ru.gxfin.common.data.naming.PhysicalNamingStrategyQuotedImpl

  datasource:
    url: jdbc:postgresql://localhost:5432/gxfin_rawmd
    username: quik
    password: 12033021
    driverClassName: org.postgresql.Driver