CREATE OR REPLACE PROCEDURE "Quik"."Orders@SavePackage"(Data character varying)
    LANGUAGE PLPGSQL
AS $$
BEGIN
    INSERT INTO "Quik"."Orders"
    (
        "ExchangeCode",
        "OrderNum",
        "Account",
        "AccountType",
        "AccruedInterest",
        "ActivationTime",
        "Balance",
        "BankAccountId",
        "BrokerRef",
        "CanceledUid",
        "Capacity",
        "ClassCode",
        "ClientCode",
        "Direction",
        "ExecType",
        "Expiry",
        "ExtOrderFlags",
        "FirmId",
        "LinkedOrder",
        "MinQuantity",
        "PassiveOnlyOrder",
        "Price",
        "Price2",
        "Quantity",
        "RejectReason",
        "Repo2Value",
        "RepoTerm",
        "RepoValue",
        "repoValueBalance",
        "SecCode",
        "SettleCode",
        "SideQualifier",
        "StartDiscount",
        "TradeDateTime",
        "TransactionId",
        "Uid",
        "UserId",
        "Value",
        "ValueEntryType",
        "Visible",
        "WithdrawDateTime",
        "Yield"
	)
    SELECT D.*
    FROM JSONB_TO_RECORDSET(JSONB_EXTRACT_PATH(Data :: JSONB, '$.objects')) AS D
    (
        "exchangeCode"      character varying(255),
        "orderNum"          character varying(50),
        "account"           character varying(50),
        "accountType"       integer,
        "accruedInterest"   numeric(24,8),
        "activationTime"    bigint,
        "balance"           numeric(24,8),
        "bankAccountId"     character varying(50),
        "brokerRef"         character varying(50),
        "canceledUid"       bigint,
        "capacity"          numeric(24,8),
        "classCode"         character varying(50),
        "clientCode"        character varying(50),
        "direction"         character varying(10),
        "execType"          integer,
        "expiry"            bigint,
        "extOrderFlags"     integer,
        "firmId"            character varying(50),
        "linkedOrder"       bigint,
        "minQuantity"       numeric(24,8),
        "passiveOnlyOrder"  smallint,
        "price"             numeric(24,8),
        "price2"            numeric(24,8),
        "quantity"          numeric(24,8),
        "rejectReason"      character varying(50),
        "repo2Value"        numeric(24,8),
        "repoTerm"          integer,
        "repoValue"         numeric(24,8),
        "repoValueBalance"  numeric(24,8),
        "secCode"           character varying(50),
        "settleCode"        character varying(50),
        "sideQualifier"     integer,
        "startDiscount"     numeric(24,8),
        "tradeDateTime"     timestamp without time zone,
        "transactionId"     bigint,
        "uid"               bigint,
        "userId"            character varying(50),
        "value"             numeric(24,8),
        "valueEntryType"    smallint,
        "visible"           numeric(24,8),
        "withdrawDateTime"  timestamp without time zone,
        "yield"             numeric(24,8)
    )
    ON CONFLICT ("ExchangeCode", "OrderNum") DO UPDATE SET
        "Account"           = EXCLUDED."Account",
        "AccountType"       = EXCLUDED."AccountType",
        "AccruedInterest"   = EXCLUDED."AccruedInterest",
        "ActivationTime"    = EXCLUDED."ActivationTime",
        "Balance"           = EXCLUDED."Balance",
        "BankAccountId"     = EXCLUDED."BankAccountId",
        "BrokerRef"         = EXCLUDED."BrokerRef",
        "CanceledUid"       = EXCLUDED."CanceledUid",
        "Capacity"          = EXCLUDED."Capacity",
        "ClassCode"         = EXCLUDED."ClassCode",
        "ClientCode"        = EXCLUDED."ClientCode",
        "Direction"         = EXCLUDED."Direction",
        "ExecType"          = EXCLUDED."ExecType",
        "Expiry"            = EXCLUDED."Expiry",
        "ExtOrderFlags"     = EXCLUDED."ExtOrderFlags",
        "FirmId"            = EXCLUDED."FirmId",
        "LinkedOrder"       = EXCLUDED."LinkedOrder",
        "MinQuantity"       = EXCLUDED."MinQuantity",
        "PassiveOnlyOrder"  = EXCLUDED."PassiveOnlyOrder",
        "Price"             = EXCLUDED."Price",
        "Price2"            = EXCLUDED."Price2",
        "Quantity"          = EXCLUDED."Quantity",
        "RejectReason"      = EXCLUDED."RejectReason",
        "Repo2Value"        = EXCLUDED."Repo2Value",
        "RepoTerm"          = EXCLUDED."RepoTerm",
        "RepoValue"         = EXCLUDED."RepoValue",
        "repoValueBalance"  = EXCLUDED."repoValueBalance",
        "SecCode"           = EXCLUDED."SecCode",
        "SettleCode"        = EXCLUDED."SettleCode",
        "SideQualifier"     = EXCLUDED."SideQualifier",
        "StartDiscount"     = EXCLUDED."StartDiscount",
        "TradeDateTime"     = EXCLUDED."TradeDateTime",
        "TransactionId"     = EXCLUDED."TransactionId",
        "Uid"               = EXCLUDED."Uid",
        "UserId"            = EXCLUDED."UserId",
        "Value"             = EXCLUDED."Value",
        "ValueEntryType"    = EXCLUDED."ValueEntryType",
        "Visible"           = EXCLUDED."Visible",
        "WithdrawDateTime"  = EXCLUDED."WithdrawDateTime",
        "Yield"             = EXCLUDED."Yield";
END;
$$;